default_stages: [commit, push]

repos:
    - repo: https://github.com/jackdewinter/pymarkdown
      rev: v0.9.9
      hooks:
          - id: pymarkdown
            verbose: true
            args:
                - --config=.pymarkdown.json
                - scan
