default_stages: [commit, push]

repos:
    - repo: https://github.com/jackdewinter/pymarkdown
      rev: main
      hooks:
          - id: pymarkdown
            args:
                - scan
            verbose: true
